// <auto-generated />
namespace NHN1721050561.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_table_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261000072_create_table_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
